### ISSUE TITLE
npm unpublish is broken

### ISSUE THREAD

**Issue by mreinstein** [npm/npme-installer#32]
when I attempt `npm unpublish --force @scope/packagename` I get an unauthorized error:

```bash
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "unpublish" "--force" "@scope/packagename"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.4
npm ERR! code E401

npm ERR! Request was not authorized : @scope%2packagename,-rev,1-ca4195af0632f22d622fe9ec6ee909f5
```

**Comment by camwest** [comment]
:+1: I'm also unable to unpublish

**Comment by mmalecki** [comment]
This has been fixed a long time ago.

**Comment by mreinstein** [comment]
Then it should have been updated a long time ago. ;)

**Comment by mmalecki** [comment]
True that @mreinstein - we've been keeping track of this bug internally and forgot to update this issue - sorry about that!

**Comment by mreinstein** [comment]
@mmalecki I don't pretend to understand npme's internal development practices but externally, it's perplexing that you would track this bug internally in another system. Why not use a public bug tracker as the one source of truth, and keep that up to date?

**Comment by mmalecki** [comment]
@mreinstein we don't use another system for tracking npmE bugs, however some of the issues extend past the installer, or even any other single repository that we have, thus we create small issues in every one of the repositories affected. This single issue has fallen through the cracks as we haven't linked it to our internal issues, and we've since made sure that all the issues have those references in them.
